[package]
name = "respring"
description = "A Rust implementation of SwiftUI's Spring."
authors = ["ktiays <cuansky@gmail.com>"]
version = "0.1.1"
edition = "2024"
license = "MIT"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = true
